/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useRef } from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { 
  Plus, 
  FileText, 
  Download, 
  Trash2, 
  Brain, 
  MessageSquare, 
  Sparkles, 
  ChevronRight, 
  ArrowLeft,
  Send,
  BookOpen,
  Copy,
  Check,
  Tag,
  RefreshCw
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { GoogleGenAI, Type } from "@google/genai";
import ReactMarkdown from 'react-markdown';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

// --- Utility ---
function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });

interface Document {
  id: string;
  title: string;
  content: string;
  createdAt: number;
}

interface Flashcard {
  question: string;
  answer: string;
}

// --- PDF Generation Helper ---
const generatePDF = (title: string, content: string) => {
  const doc = new jsPDF();
  const margin = 15; // Reduced margin for more content space
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - (margin * 2);
  const lineHeight = 6; // Reduced line height for better density
  const pageHeight = doc.internal.pageSize.getHeight();

  const addPageDecorations = () => {
    doc.setDrawColor(226, 232, 240); // Slate 200
    doc.setLineWidth(0.1);
    doc.rect(5, 5, pageWidth - 10, pageHeight - 10);
  };

  // Header background for title
  doc.setFillColor(248, 250, 252);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setDrawColor(16, 185, 129);
  doc.setLineWidth(1);
  doc.line(0, 40, pageWidth, 40);

  // Initial page decoration
  addPageDecorations();

  doc.setFontSize(24);
  doc.setTextColor(16, 185, 129); // Emerald 500
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by StudyFlow • ${new Date().toLocaleDateString()}`, margin, 33);
  
  let y = 50;
  const lines = content.split('\n');
  let tableRows: string[][] = [];
  let inTable = false;

  const checkPage = (height: number) => {
    if (y + height > 280) {
      doc.addPage();
      addPageDecorations();
      y = 20;
    }
  };

  lines.forEach((line) => {
    const trimmed = line.trim();
    
    // Table detection
    if (trimmed.startsWith('|') && trimmed.includes('|')) {
      if (trimmed.includes('---')) return; // Skip separator line
      const cells = trimmed.split('|').filter((_, i, arr) => i > 0 && i < arr.length - 1).map(c => c.trim());
      if (cells.length > 0) {
        tableRows.push(cells);
        inTable = true;
        return;
      }
    } else if (inTable) {
      // End of table
      if (tableRows.length > 0) {
        autoTable(doc, {
          head: [tableRows[0]],
          body: tableRows.slice(1),
          startY: y,
          margin: { left: margin, right: margin },
          theme: 'grid',
          headStyles: { fillColor: [16, 185, 129], textColor: [255, 255, 255], fontStyle: 'bold' },
          styles: { font: 'helvetica', fontSize: 9, cellPadding: 2 },
          alternateRowStyles: { fillColor: [249, 250, 251] },
          didDrawPage: () => addPageDecorations()
        });
        y = (doc as any).lastAutoTable.finalY + 8;
      }
      tableRows = [];
      inTable = false;
    }

    if (!trimmed) {
      y += 3; // Reduced spacing for empty lines
      return;
    }

    // Header detection
    if (trimmed.startsWith('#')) {
      const level = (trimmed.match(/^#+/) || ['#'])[0].length;
      const text = trimmed.replace(/^#+\s+/, '');
      checkPage(12);
      doc.setFontSize(level === 1 ? 16 : 14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42); // Slate 900
      doc.text(text, margin, y);
      y += 8;
      return;
    }

    // Subtopic / Bold detection
    if ((trimmed.startsWith('**') && trimmed.endsWith('**')) || (trimmed.startsWith('__') && trimmed.endsWith('__'))) {
      const text = trimmed.replace(/[*_]/g, '');
      checkPage(8);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30, 41, 59); // Slate 800
      doc.text(text, margin, y);
      y += 6;
      return;
    }

    // List detection
    if (trimmed.startsWith('- ') || trimmed.startsWith('* ') || trimmed.startsWith('+ ')) {
      const text = '• ' + trimmed.substring(2).replace(/[*_]/g, '');
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(51, 65, 85); // Slate 700
      const splitText = doc.splitTextToSize(text, contentWidth - 5);
      checkPage(splitText.length * lineHeight);
      doc.text(splitText, margin + 5, y);
      y += splitText.length * lineHeight;
      return;
    }

    // Normal text
    const cleanText = trimmed.replace(/[*_]/g, '');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85); // Slate 700
    const splitText = doc.splitTextToSize(cleanText, contentWidth);
    checkPage(splitText.length * lineHeight);
    doc.text(splitText, margin, y);
    y += splitText.length * lineHeight + 1;
  });

  // Final table if content ends with one
  if (inTable && tableRows.length > 0) {
    autoTable(doc, {
      head: [tableRows[0]],
      body: tableRows.slice(1),
      startY: y,
      margin: { left: margin, right: margin },
      theme: 'grid',
      headStyles: { fillColor: [16, 185, 129], textColor: [255, 255, 255], fontStyle: 'bold' },
      styles: { font: 'helvetica', fontSize: 9, cellPadding: 2 }
    });
  }

  doc.save(`${title.replace(/\s+/g, '_')}.pdf`);
};

export default function App() {
  const [documents, setDocuments] = useState<Document[]>([]);
  const [activeDocId, setActiveDocId] = useState<string | null>(null);
  const [isImporting, setIsImporting] = useState(false);
  const [pasteText, setPasteText] = useState('');
  const [newDocTitle, setNewDocTitle] = useState('');
  const [importMode, setImportMode] = useState<'new' | 'append'>('new');
  const [selectedAppendId, setSelectedAppendId] = useState<string | null>(null);
  const [lastAction, setLastAction] = useState<{ type: 'created' | 'updated', doc: Document } | null>(null);
  
  // Study Tools State
  const [flashcards, setFlashcards] = useState<Flashcard[]>([]);
  const [summary, setSummary] = useState('');
  const [chatMessages, setChatMessages] = useState<{ role: 'user' | 'ai', text: string }[]>([]);
  const [chatInput, setChatInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [activeTool, setActiveTool] = useState<'none' | 'flashcards' | 'summary' | 'chat'>('none');
  const [flashcardCount, setFlashcardCount] = useState(5);
  const [flashcardKeywords, setFlashcardKeywords] = useState('');

  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const saved = localStorage.getItem('studyflow_docs');
    if (saved) {
      setDocuments(JSON.parse(saved));
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('studyflow_docs', JSON.stringify(documents));
  }, [documents]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages]);

  const activeDoc = documents.find(d => d.id === activeDocId);

  const handleImport = () => {
    if (!pasteText.trim()) return;

    let targetDoc: Document | undefined;

    if (importMode === 'new') {
      targetDoc = {
        id: Math.random().toString(36).substr(2, 9),
        title: newDocTitle || `Study Notes ${new Date().toLocaleDateString()}`,
        content: pasteText,
        createdAt: Date.now(),
      };
      setDocuments([targetDoc, ...documents]);
      setLastAction({ type: 'created', doc: targetDoc });
    } else if (selectedAppendId) {
      const existingDoc = documents.find(d => d.id === selectedAppendId);
      if (existingDoc) {
        targetDoc = { ...existingDoc, content: existingDoc.content + '\n\n' + pasteText };
        setDocuments(documents.map(d => d.id === selectedAppendId ? targetDoc! : d));
        setLastAction({ type: 'updated', doc: targetDoc });
      }
    }

    setPasteText('');
    setNewDocTitle('');
    setSelectedAppendId(null);
  };

  const deleteDoc = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setDocuments(documents.filter(d => d.id !== id));
    if (activeDocId === id) setActiveDocId(null);
  };

  const generateAIContent = async (type: 'flashcards' | 'summary' | 'chat') => {
    if (!activeDoc) return;
    setIsLoading(true);

    try {
      const model = "gemini-3-flash-preview";
      let prompt = "";

      if (type === 'flashcards') {
        prompt = `Based on the following study material, generate exactly ${flashcardCount} high-quality flashcards. 
        ${flashcardKeywords ? `Focus specifically on these keywords or concepts: ${flashcardKeywords}.` : ''}
        Return ONLY a JSON array of objects with "question" and "answer" properties.
        Material: ${activeDoc.content.substring(0, 5000)}`;
        
        const response = await ai.models.generateContent({
          model,
          contents: prompt,
          config: { 
            responseMimeType: "application/json",
            responseSchema: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  question: { type: Type.STRING },
                  answer: { type: Type.STRING }
                },
                required: ["question", "answer"]
              }
            }
          }
        });
        setFlashcards(JSON.parse(response.text || '[]'));
      } else if (type === 'summary') {
        prompt = `Summarize the following study material in a clear, structured way for a student. 
        Use bullet points and bold key terms.
        Material: ${activeDoc.content.substring(0, 8000)}`;
        
        const response = await ai.models.generateContent({
          model,
          contents: prompt,
        });
        setSummary(response.text || 'Failed to generate summary.');
      }
    } catch (error) {
      console.error("AI Error:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleChat = async () => {
    if (!chatInput.trim() || !activeDoc) return;

    const userMsg = chatInput;
    setChatMessages(prev => [...prev, { role: 'user', text: userMsg }]);
    setChatInput('');
    setIsLoading(true);

    try {
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: `Context from my study document: ${activeDoc.content.substring(0, 10000)}
        
        Question: ${userMsg}
        
        Please explain clearly. If I ask to explain like I'm five, do so. Otherwise, be a helpful study tutor.`,
      });
      
      setChatMessages(prev => [...prev, { role: 'ai', text: response.text || "I'm sorry, I couldn't process that." }]);
    } catch (error) {
      console.error("Chat Error:", error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#F8F9FA] text-[#1A1A1A] font-sans selection:bg-emerald-100">
      {/* Header */}
      <header className="sticky top-0 z-30 bg-white/80 backdrop-blur-md border-b border-black/5 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-emerald-500 rounded-xl flex items-center justify-center text-white shadow-lg shadow-emerald-200">
            <BookOpen size={24} />
          </div>
          <div>
            <h1 className="text-xl font-bold tracking-tight">StudyFlow</h1>
            <p className="text-xs text-black/40 font-medium uppercase tracking-wider">Student Companion</p>
          </div>
        </div>
        
        {activeDocId && (
          <button 
            onClick={() => setActiveDocId(null)}
            className="flex items-center gap-2 text-sm font-medium text-black/60 hover:text-black transition-colors"
          >
            <ArrowLeft size={18} />
            Back to Library
          </button>
        )}
      </header>

      <main className="max-w-5xl mx-auto p-6">
        <AnimatePresence mode="wait">
          {!activeDocId ? (
            <motion.div 
              key="library"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="space-y-8"
            >
              {/* Import Section */}
              <section className="bg-white rounded-lg p-8 border border-black/5 shadow-sm">
                <div className="flex items-center justify-between mb-6">
                  <div>
                    <h2 className="text-2xl font-bold">New Study Material</h2>
                    <p className="text-black/50">Paste text from ChatGPT or Gemini to create a study document.</p>
                  </div>
                  <Sparkles className="text-emerald-500" />
                </div>

                <div className="space-y-6">
                  <div className="relative">
                    <textarea 
                      placeholder="Paste your AI chat text here..."
                      value={pasteText}
                      onChange={(e) => setPasteText(e.target.value)}
                      className="w-full h-48 px-4 py-3 rounded-2xl bg-black/5 border-transparent focus:bg-white focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10 transition-all outline-none resize-none text-sm leading-relaxed"
                    />
                    {pasteText && (
                      <button 
                        onClick={() => setPasteText('')}
                        className="absolute top-3 right-3 p-1.5 bg-black/5 hover:bg-black/10 rounded-lg text-black/40 transition-colors"
                      >
                        <Trash2 size={14} />
                      </button>
                    )}
                  </div>
                  
                  {documents.length > 0 && pasteText.trim() && (
                    <div className="space-y-4 animate-in fade-in slide-in-from-top-2 duration-300">
                      <p className="text-sm font-bold text-black/60 uppercase tracking-wider">How would you like to save this?</p>
                      <div className="flex gap-4 p-1 bg-black/5 rounded-2xl w-full">
                        <button 
                          onClick={() => setImportMode('new')}
                          className={cn(
                            "flex-1 py-3 rounded-xl text-sm font-bold transition-all flex items-center justify-center gap-2",
                            importMode === 'new' ? "bg-white shadow-md text-emerald-600" : "text-black/40 hover:text-black/60"
                          )}
                        >
                          <Plus size={18} />
                          Create New PDF
                        </button>
                        <button 
                          onClick={() => setImportMode('append')}
                          className={cn(
                            "flex-1 py-3 rounded-xl text-sm font-bold transition-all flex items-center justify-center gap-2",
                            importMode === 'append' ? "bg-white shadow-md text-emerald-600" : "text-black/40 hover:text-black/60"
                          )}
                        >
                          <FileText size={18} />
                          Append to Existing PDF
                        </button>
                      </div>
                    </div>
                  )}

                  {importMode === 'new' && pasteText.trim() && (
                    <div className="animate-in fade-in slide-in-from-top-2 duration-300">
                      <input 
                        type="text"
                        placeholder="Enter a title for your new PDF..."
                        value={newDocTitle}
                        onChange={(e) => setNewDocTitle(e.target.value)}
                        className="w-full px-4 py-3 rounded-xl bg-black/5 border-transparent focus:bg-white focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10 transition-all outline-none"
                      />
                    </div>
                  )}

                  {importMode === 'append' && documents.length > 0 && pasteText.trim() && (
                    <div className="space-y-3 animate-in fade-in slide-in-from-top-2 duration-300">
                      <p className="text-sm font-bold text-black/60 uppercase tracking-wider">Select a PDF to append to:</p>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 max-h-48 overflow-y-auto p-1">
                        {documents.map(d => (
                          <button
                            key={d.id}
                            onClick={() => setSelectedAppendId(d.id)}
                            className={cn(
                              "px-4 py-3 rounded-xl text-left text-sm font-medium border transition-all flex items-center gap-3",
                              selectedAppendId === d.id 
                                ? "bg-emerald-50 border-emerald-500 text-emerald-700 shadow-sm" 
                                : "bg-white border-black/5 hover:border-black/10 text-black/60"
                            )}
                          >
                            <div className={cn(
                              "w-2 h-2 rounded-full",
                              selectedAppendId === d.id ? "bg-emerald-500" : "bg-black/10"
                            )} />
                            <span className="truncate">{d.title}</span>
                          </button>
                        ))}
                      </div>
                    </div>
                  )}

                  <div className="flex flex-col sm:flex-row gap-3 mt-4">
                    <button 
                      onClick={handleImport}
                      disabled={!pasteText.trim() || (importMode === 'append' && !selectedAppendId)}
                      className="flex-1 py-4 bg-emerald-500 hover:bg-emerald-600 disabled:bg-black/10 disabled:text-black/20 text-white font-bold rounded-2xl shadow-lg shadow-emerald-200 transition-all flex items-center justify-center gap-2"
                    >
                      <Check size={20} />
                      {importMode === 'new' ? 'Create PDF' : 'Update PDF'}
                    </button>
                  </div>

                  {/* Success State */}
                  <AnimatePresence>
                    {lastAction && (
                      <motion.div 
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -10 }}
                        className="mt-6 p-6 bg-emerald-50 rounded-3xl border border-emerald-100 flex flex-col md:flex-row items-center justify-between gap-4"
                      >
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 bg-emerald-500 rounded-full flex items-center justify-center text-white">
                            <Check size={20} />
                          </div>
                          <div>
                            <p className="font-bold text-emerald-900">PDF {lastAction.type === 'created' ? 'Created' : 'Updated'} Successfully!</p>
                            <p className="text-sm text-emerald-700/70">{lastAction.doc.title}</p>
                          </div>
                        </div>
                        <div className="flex gap-2 w-full md:w-auto">
                          <button 
                            onClick={() => generatePDF(lastAction.doc.title, lastAction.doc.content)}
                            className="flex-1 md:flex-none px-4 py-2 bg-emerald-600 text-white text-sm font-bold rounded-xl hover:bg-emerald-700 transition-all flex items-center justify-center gap-2"
                          >
                            <Download size={16} />
                            Download Now
                          </button>
                          <button 
                            onClick={() => {
                              setActiveDocId(lastAction.doc.id);
                              setLastAction(null);
                            }}
                            className="flex-1 md:flex-none px-4 py-2 bg-white text-emerald-600 text-sm font-bold rounded-xl border border-emerald-200 hover:bg-emerald-50 transition-all flex items-center justify-center gap-2"
                          >
                            Open Study Tools
                          </button>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              </section>

              {/* Library Grid */}
              <section>
                <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                  <FileText size={20} className="text-black/40" />
                  Your Library
                </h3>
                {documents.length === 0 ? (
                  <div className="text-center py-20 bg-white rounded-lg border border-dashed border-black/10">
                    <p className="text-black/30 font-medium">No documents yet. Start by pasting some text above!</p>
                  </div>
                ) : (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {documents.map(doc => (
                      <motion.div 
                        key={doc.id}
                        layoutId={doc.id}
                        onClick={() => setActiveDocId(doc.id)}
                        className="group bg-white p-6 rounded-lg border border-black/5 hover:border-emerald-500/30 hover:shadow-xl hover:shadow-emerald-500/5 transition-all cursor-pointer relative"
                      >
                        <div className="flex justify-between items-start mb-4">
                          <div className="w-12 h-12 bg-emerald-50 rounded-2xl flex items-center justify-center text-emerald-600">
                            <FileText size={24} />
                          </div>
                          <button 
                            onClick={(e) => deleteDoc(doc.id, e)}
                            className="p-2 text-black/20 hover:text-red-500 transition-colors"
                          >
                            <Trash2 size={18} />
                          </button>
                        </div>
                        <h4 className="font-bold text-lg mb-1 group-hover:text-emerald-600 transition-colors">{doc.title}</h4>
                        <p className="text-sm text-black/40 mb-4">
                          {new Date(doc.createdAt).toLocaleDateString()} • {doc.content.split(' ').length} words
                        </p>
                        <div className="flex items-center text-sm font-bold text-emerald-600 opacity-0 group-hover:opacity-100 transition-all transform translate-x-[-10px] group-hover:translate-x-0">
                          Open Study Tools <ChevronRight size={16} />
                        </div>
                      </motion.div>
                    ))}
                  </div>
                )}
              </section>
            </motion.div>
          ) : (
            <motion.div 
              key="document-view"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="space-y-6"
            >
              {/* Active Doc Header */}
              <div className="bg-white p-8 rounded-lg border border-black/5 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-6">
                <div>
                  <h2 className="text-3xl font-bold mb-2">{activeDoc.title}</h2>
                  <div className="flex items-center gap-4 text-sm text-black/40 font-medium">
                    <span>{new Date(activeDoc.createdAt).toLocaleDateString()}</span>
                    <span>•</span>
                    <span>{activeDoc.content.split(' ').length} words</span>
                  </div>
                </div>
                <button 
                  onClick={() => generatePDF(activeDoc.title, activeDoc.content)}
                  className="px-6 py-3 bg-black text-white rounded-2xl font-bold flex items-center justify-center gap-2 hover:bg-black/80 transition-all shadow-lg"
                >
                  <Download size={20} />
                  Download PDF
                </button>
              </div>

              {/* Study Tools Grid */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <button 
                  onClick={() => { setActiveTool('flashcards'); generateAIContent('flashcards'); }}
                  className={cn(
                    "p-6 rounded-lg border transition-all flex flex-col items-center text-center gap-3",
                    activeTool === 'flashcards' ? "bg-emerald-500 border-emerald-500 text-white shadow-lg shadow-emerald-200" : "bg-white border-black/5 hover:border-emerald-500/30"
                  )}
                >
                  <Brain size={32} />
                  <div>
                    <p className="font-bold">Generate Flashcards</p>
                    <p className={cn("text-xs", activeTool === 'flashcards' ? "text-white/70" : "text-black/40")}>Test your knowledge</p>
                  </div>
                </button>
                <button 
                  onClick={() => { setActiveTool('summary'); generateAIContent('summary'); }}
                  className={cn(
                    "p-6 rounded-lg border transition-all flex flex-col items-center text-center gap-3",
                    activeTool === 'summary' ? "bg-emerald-500 border-emerald-500 text-white shadow-lg shadow-emerald-200" : "bg-white border-black/5 hover:border-emerald-500/30"
                  )}
                >
                  <FileText size={32} />
                  <div>
                    <p className="font-bold">Summarize PDF</p>
                    <p className={cn("text-xs", activeTool === 'summary' ? "text-white/70" : "text-black/40")}>Quick review points</p>
                  </div>
                </button>
                <button 
                  onClick={() => setActiveTool('chat')}
                  className={cn(
                    "p-6 rounded-lg border transition-all flex flex-col items-center text-center gap-3",
                    activeTool === 'chat' ? "bg-emerald-500 border-emerald-500 text-white shadow-lg shadow-emerald-200" : "bg-white border-black/5 hover:border-emerald-500/30"
                  )}
                >
                  <MessageSquare size={32} />
                  <div>
                    <p className="font-bold">Ask Questions about PDF</p>
                    <p className={cn("text-xs", activeTool === 'chat' ? "text-white/70" : "text-black/40")}>Ask anything</p>
                  </div>
                </button>
              </div>

              {/* Tool Content Area */}
              <AnimatePresence mode="wait">
                {activeTool !== 'none' && (
                  <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: 20 }}
                    className="bg-white rounded-lg border border-black/5 shadow-sm overflow-hidden"
                  >
                    {activeTool === 'flashcards' && (
                      <div className="p-8">
                        <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-6">
                          <div>
                            <h3 className="text-xl font-bold flex items-center gap-2 mb-1">
                              <Brain className="text-emerald-500" />
                              Study Flashcards
                            </h3>
                            <p className="text-xs text-black/40 font-medium">Customize your generation settings below</p>
                          </div>
                          
                          <div className="flex flex-wrap items-center gap-4">
                            <div className="flex items-center gap-3 bg-black/5 p-1 rounded-xl">
                              <span className="text-xs font-bold text-black/40 pl-3">COUNT</span>
                              <div className="flex items-center gap-1">
                                {[3, 5, 8, 10].map(n => (
                                  <button
                                    key={n}
                                    onClick={() => setFlashcardCount(n)}
                                    className={cn(
                                      "w-8 h-8 rounded-lg text-xs font-bold transition-all",
                                      flashcardCount === n ? "bg-white shadow-sm text-emerald-600" : "text-black/30 hover:text-black/60"
                                    )}
                                  >
                                    {n}
                                  </button>
                                ))}
                              </div>
                            </div>
                            
                            <div className="flex-1 md:w-64 relative">
                              <input 
                                type="text"
                                placeholder="Keywords (e.g. 'Photosynthesis')"
                                value={flashcardKeywords}
                                onChange={(e) => setFlashcardKeywords(e.target.value)}
                                className="w-full px-4 py-2 bg-black/5 border-transparent rounded-xl text-xs font-medium focus:bg-white focus:ring-2 focus:ring-emerald-500/20 outline-none transition-all"
                              />
                              <Tag size={14} className="absolute right-3 top-2.5 text-black/20" />
                            </div>

                            <button 
                              onClick={() => generateAIContent('flashcards')}
                              disabled={isLoading}
                              className="px-4 py-2 bg-emerald-500 hover:bg-emerald-600 text-white text-xs font-bold rounded-xl transition-all flex items-center gap-2 shadow-lg shadow-emerald-200 disabled:opacity-50"
                            >
                              <RefreshCw size={14} className={isLoading ? "animate-spin" : ""} />
                              Regenerate
                            </button>
                          </div>
                        </div>

                        {isLoading ? (
                          <div className="flex flex-col items-center justify-center py-20 gap-4">
                            <div className="w-8 h-8 border-4 border-emerald-500 border-t-transparent rounded-full animate-spin" />
                            <p className="text-sm font-medium text-black/40">Generating cards...</p>
                          </div>
                        ) : (
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            {flashcards.map((card, i) => (
                              <div key={i} className="group p-6 rounded-2xl bg-black/5 hover:bg-emerald-50 transition-all">
                                <p className="text-xs font-bold text-emerald-600 uppercase tracking-widest mb-2">Question</p>
                                <p className="font-bold mb-4">{card.question}</p>
                                <div className="h-px bg-black/5 mb-4" />
                                <p className="text-xs font-bold text-black/30 uppercase tracking-widest mb-2">Answer</p>
                                <p className="text-black/70">{card.answer}</p>
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    )}

                    {activeTool === 'summary' && (
                      <div className="p-8">
                        <div className="flex items-center justify-between mb-6">
                          <h3 className="text-xl font-bold flex items-center gap-2">
                            <FileText className="text-emerald-500" />
                            Material Summary
                          </h3>
                          {!isLoading && summary && (
                            <button 
                              onClick={() => navigator.clipboard.writeText(summary)}
                              className="flex items-center gap-2 text-xs font-bold text-black/40 hover:text-emerald-600 transition-colors"
                            >
                              <Copy size={16} />
                              Copy Summary
                            </button>
                          )}
                        </div>
                        {isLoading ? (
                          <div className="flex flex-col items-center justify-center py-20 gap-4">
                            <div className="w-8 h-8 border-4 border-emerald-500 border-t-transparent rounded-full animate-spin" />
                            <p className="text-sm font-medium text-black/40">Synthesizing points...</p>
                          </div>
                        ) : (
                          <div className="prose prose-emerald max-w-none">
                            <ReactMarkdown>{summary}</ReactMarkdown>
                          </div>
                        )}
                      </div>
                    )}

                    {activeTool === 'chat' && (
                      <div className="flex flex-col h-[600px]">
                        <div className="p-6 border-b border-black/5 flex items-center justify-between">
                          <h3 className="text-xl font-bold flex items-center gap-2">
                            <MessageSquare className="text-emerald-500" />
                            AI Study Tutor
                          </h3>
                          <span className="text-xs font-bold px-2 py-1 bg-emerald-100 text-emerald-700 rounded-md">Online</span>
                        </div>
                        
                        <div className="flex-1 overflow-y-auto p-6 space-y-4">
                          {chatMessages.length === 0 && (
                            <div className="text-center py-20">
                              <div className="w-16 h-16 bg-emerald-50 rounded-full flex items-center justify-center mx-auto mb-4 text-emerald-500">
                                <Sparkles size={32} />
                              </div>
                              <p className="text-black/40 font-medium">Ask me anything about your study material!</p>
                              <p className="text-xs text-black/30 mt-1">Try: "Explain the main concept like I'm 5"</p>
                            </div>
                          )}
                          {chatMessages.map((msg, i) => (
                            <div key={i} className={cn(
                              "flex",
                              msg.role === 'user' ? "justify-end" : "justify-start"
                            )}>
                              <div className={cn(
                                "max-w-[80%] p-4 rounded-2xl text-sm",
                                msg.role === 'user' ? "bg-emerald-500 text-white rounded-tr-none" : "bg-black/5 text-black rounded-tl-none"
                              )}>
                                {msg.role === 'ai' ? (
                                  <div className="prose prose-sm prose-emerald">
                                    <ReactMarkdown>{msg.text}</ReactMarkdown>
                                  </div>
                                ) : (
                                  msg.text
                                )}
                              </div>
                            </div>
                          ))}
                          {isLoading && (
                            <div className="flex justify-start">
                              <div className="bg-black/5 p-4 rounded-2xl rounded-tl-none flex gap-1">
                                <div className="w-1.5 h-1.5 bg-black/20 rounded-full animate-bounce" />
                                <div className="w-1.5 h-1.5 bg-black/20 rounded-full animate-bounce [animation-delay:0.2s]" />
                                <div className="w-1.5 h-1.5 bg-black/20 rounded-full animate-bounce [animation-delay:0.4s]" />
                              </div>
                            </div>
                          )}
                          <div ref={chatEndRef} />
                        </div>

                        <div className="p-4 border-t border-black/5 space-y-3">
                          <div className="flex gap-2">
                            <button 
                              onClick={() => { setChatInput("Explain the main concept like I'm 5"); }}
                              className="px-3 py-1.5 bg-emerald-50 text-emerald-600 text-xs font-bold rounded-lg hover:bg-emerald-100 transition-colors"
                            >
                              Explain Like I'm 5
                            </button>
                            <button 
                              onClick={() => { setChatInput("Give me a standard explanation of this material"); }}
                              className="px-3 py-1.5 bg-black/5 text-black/60 text-xs font-bold rounded-lg hover:bg-black/10 transition-colors"
                            >
                              Standard Explanation
                            </button>
                          </div>
                          <div className="flex gap-2">
                            <input 
                              type="text"
                              placeholder="Type your question..."
                              value={chatInput}
                              onChange={(e) => setChatInput(e.target.value)}
                              onKeyDown={(e) => e.key === 'Enter' && handleChat()}
                              className="flex-1 px-4 py-3 rounded-xl bg-black/5 border-transparent focus:bg-white focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10 transition-all outline-none"
                            />
                            <button 
                              onClick={handleChat}
                              disabled={isLoading || !chatInput.trim()}
                              className="p-3 bg-emerald-500 hover:bg-emerald-600 disabled:bg-black/10 text-white rounded-xl shadow-lg shadow-emerald-200 transition-all"
                            >
                              <Send size={20} />
                            </button>
                          </div>
                        </div>
                      </div>
                    )}
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Raw Content Preview */}
              <div className="bg-white p-8 rounded-lg border border-black/5 shadow-sm">
                <div className="flex items-center justify-between mb-6">
                  <h3 className="text-lg font-bold">Document Content</h3>
                  <button 
                    onClick={() => {
                      navigator.clipboard.writeText(activeDoc.content);
                    }}
                    className="p-2 text-black/20 hover:text-emerald-500 transition-colors"
                  >
                    <Copy size={18} />
                  </button>
                </div>
                <div className="prose prose-emerald max-w-none text-black/70 whitespace-pre-wrap">
                  {activeDoc.content}
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      {/* Footer */}
      <footer className="mt-20 py-10 border-t border-black/5 text-center">
        <p className="text-sm text-black/30 font-medium">StudyFlow • Built for Students</p>
      </footer>
    </div>
  );
}
